In [1]:
import numpy as np

In [7]:
x = np.array([[
    [23,50],
    [7,12],
],[
    [57,67],
    [99,43]
],[
    [75,21],
    [57,12]
],[
    [87,26],
    [18,84]
]])

A = np.array([
    [23,50,19],
    [7,12,109],
    [57,67,98]
])
B = np.array([17,22,19])

print(A*B)
print(' ')
print(A@B)

[[ 391 1100  361]
 [ 119  264 2071]
 [ 969 1474 1862]]
 
[1852 2454 4305]


In [15]:
a = np.array([
    [23,50,19],
    [7,12,109],
    [57,67,98]              
])


print('Transpose dari a = ', a.transpose())
print()
print('Determinant dari a = ', np.linalg.det(a))
print()
print('Inverse dari a = ', np.linalg.inv(a))

Transpose dari a =  [[ 23   7  57]
 [ 50  12  67]
 [ 19 109  98]]

Determinant dari a =  131344.0000000002

Inverse dari a =  [[-0.0466485  -0.02761451  0.03975819]
 [ 0.04208034  0.00891552 -0.01807467]
 [-0.00163692  0.0099662  -0.00056341]]
